#!/bin/bash

# node.js using PPA (for statsd)
sudo apt-get install python-software-properties
sudo apt-get install nodejs npm

# Install git to get statsd
sudo apt-get install git

# System level dependencies for Graphite
sudo apt-get install memcached python-dev python-pip sqlite3 libcairo2 \
 libcairo2-dev python-cairo pkg-config

# Get latest pip
sudo pip install --upgrade pip

# Install carbon and graphite deps
cat > /tmp/graphite_reqs.txt << EOF
django==1.3
python-memcached
django-tagging==0.3.1
twisted<12.0
whisper==0.9.12
carbon==0.9.12
graphite-web==0.9.12
EOF

sudo pip install -r /tmp/graphite_reqs.txt

#
# Configure carbon
#
cd /opt/graphite/conf/
sudo cp carbon.conf.example carbon.conf

# Create storage schema and copy it over
# Using the sample as provided in the statsd README
# https://github.com/etsy/statsd#graphite-schema

cat >> /tmp/storage-schemas.conf << EOF
# Schema definitions for Whisper files. Entries are scanned in order,
# and first match wins. This file is scanned for changes every 60 seconds.
#
#  [name]
#  pattern = regex
#  retentions = timePerPoint:timeToStore, timePerPoint:timeToStore, ...
[stats]
priority = 110
pattern = ^stats\..*
retentions = 10s:6h,1m:7d,10m:1y
EOF

sudo cp /tmp/storage-schemas.conf storage-schemas.conf

# Make sure log dir exists for webapp
sudo mkdir -p /opt/graphite/storage/log/webapp

# Copy over the local settings file and initialize database
cd /opt/graphite/webapp/graphite/
sudo cp local_settings.py.example local_settings.py
sudo python manage.py syncdb  # Follow the prompts, creating a superuser is optional

# statsd
cd /opt && sudo git clone git://github.com/etsy/statsd.git

# StatsD configuration
cat >> /tmp/localConfig.js << EOF
{
  graphitePort: 2003
, graphiteHost: "127.0.0.1"
, port: 8125
}
EOF

sudo cp /tmp/localConfig.js /opt/statsd/localConfig.js

# Install apache & utilities
sudo apt-get install apache2 apache2-mpm-worker apache2-utils apache2.2-bin apache2.2-common libapache2-mod-python memcached  libapache2-mod-wsgi

# apache config and startup
sudo cp /opt/graphite/examples/example-graphite-vhost.conf /etc/apache2/sites-available/default
sudo cp /opt/graphite/conf/graphite.wsgi.example /opt/graphite/conf/graphite.wsgi
sudo chown -R www-data:www-data /opt/graphite/storage
# Update WSGI Directory
sudo mkdir -p /etc/httpd/wsgi
sudo sed -i 's/run\/wsgi/\/etc\/httpd\/wsgi/' /etc/apache2/sites-available/default
# Update configuration to listen on port 8080, we'll replace the default web-ui with Graphana
sudo sed -i '1 i\Listen 8080' /etc/apache2/sites-available/default
sudo sed -i 's/*:80/*:8080' /etc/apache2/sites-available/default
sudo service apache2 restart

# Grafana installation
cd /tmp
wget http://grafanarel.s3.amazonaws.com/grafana-1.5.4.tar.gz
tar -xzf grafana-1.5.4.tar.gz
sudo cp -rf grafana-1.5.4 /opt/grafana

cat >> /tmp/grafana-web.config << EOF
<VirtualHost *:80>
        DocumentRoot "/opt/grafana"
</VirtualHost>
EOF

sudo cat /tmp/grafana-web.config >> /etc/apache2/sites-available/default

# ElasticSearch for Grafana dashboards - install from public repo
cd /tmp
# Requires Java to run
sudo apt-get install openjdk-7-jre
# Elasticsearch repo for 1.2 
wget -O - http://packages.elasticsearch.org/GPG-KEY-elasticsearch | sudo apt-key add -
sudo echo 'deb http://packages.elasticsearch.org/elasticsearch/1.2/debian stable main' >> /etc/apt/sources.list
sudo apt-get install elasticsearch

# Start Carbon
sudo /opt/graphite/bin/carbon-cache.py start

# Should be all done here. Can start statsd for some sample stats.
